#!/bin/bash

let upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
let secs=$((${upSeconds}%60))
let mins=$((${upSeconds}/60%60))
let hours=$((${upSeconds}/3600%24))
let days=$((${upSeconds}/86400))

# get info ========================
UPTIME=`printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs"`
FREEMEM=$((`cat /proc/meminfo | grep MemFree | awk {'print $2'}`/1024))
TOTMEM=$((`cat /proc/meminfo | grep MemTotal | awk {'print $2'}`/1024))

IPLAN=$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
if [[ -z "${IPLAN}" ]]; then
    IPLAN="None"
fi
IPWLAN=$(ip addr show wlan0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
if [[ -z "${IPWLAN}" ]]; then
    IPWLAN="None"
fi

DF=`df -h | grep /dev/mmcblk0p2 | awk {'print $3 "B (Free) / " $2 "B (Total)"'}`
CPUTEMP=$((`cat /sys/class/thermal/thermal_zone0/temp`/1000*9/5+32))

# get the load averages
read one five fifteen rest < /proc/loadavg

# set colors =========================
W="\e[0;39m"
R="\e[1;31m"
G="\e[1;32m"

# ======================================

figlet `uname -n`

echo -e "${G}
`date +"%A, %e %B %Y, %r"`
`uname -srmo`
`lsb_release -d`
`lsb_release -c`
${R}
Uptime.............: ${W}${UPTIME}${R}
Memory.............: ${W}${FREEMEM} MB (Free) / ${TOTMEM} MB (Total)${R}
Storage............: ${W}${DF}${R}
Load Averages......: ${W}${one}, ${five}, ${fifteen} (1, 5, 15 min)${R}
CPU Temperature....: ${W}${CPUTEMP} F${R}
Running Processes..: ${W}`ps ax | wc -l | tr -d " "`${R}
LAN  IP Addr.......: ${W}${IPLAN}${R}
WiFi IP Addr.......: ${W}${IPWLAN}${W}"
echo "  "
